title: LearnPF
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

 
 
callouts:
 note:
    title: Practice!
    color: green 
example:
    title: Example
    color: yellow 
