title: LearnPF
description: Debate, made free
 
url:https://learnpf.github.io/crossfire.html

  
 color_scheme: dark

  
  
callouts: 
 note:
    title: Practice!
    color: green 
delete:
    title: Example
    color: yellow 
