title: LearnPF
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

 
color_scheme: dark
 
callouts:
 note:
    title: Practice!
    color: Purple 
example:
    title: Example
    color: Yellow 
