name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  # Build job
 github-pages-build:
    name: Build (github-pages gem)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: false
    - name: Bundle Install
      run: bundle install
      env:
        BUNDLE_GEMFILE: fixtures/Gemfile-github-pages
    - name: Build Site
      run: bundle exec jekyll build
      env:
        BUNDLE_GEMFILE: fixtures/Gemfile-github-pages
